// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutMediaOverlay from '@/components/sections/about/AboutMediaOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutMediaOverlay
          tag="About Tafakkur"
          title="Meet Esmael Ali"
          description="With a BS in Computer Science and deep expertise in systems analysis and IT operations, Esmael Ali bridges the gap between technical complexity and simple business growth."
          imageSrc="https://storage.googleapis.com/webild/users/user_3FIKUSP6IUF6tBtzEvQnPfoz1vV/uploaded-1781757562381-v9v4f3wy.png"
        />
        </SectionErrorBoundary>
      </div>
  );
}
