// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Get Started"
          text="Ready to scale your business? Let's talk strategy."
          primaryButton={{
            text: "Contact Esmael Now",
            href: "mailto:esmaelali699@gmail.com",
          }}
          secondaryButton={{
            text: "View Case Studies",
            href: "#",
          }}
        />
        </SectionErrorBoundary>
      </div>
  );
}
