// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Get Started"
          text="Ready to scale your business? Let's talk strategy."
          primaryButton={{
            text: "Message on WhatsApp",
            href: "https://wa.me/17206284541",
          }}
          secondaryButton={{
            text: "Connect on LinkedIn",
            href: "https://www.linkedin.com/in/esmael-a-a537bb18b",
          }}
        />
        </SectionErrorBoundary>
      </div>
  );
}
