// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSplitMedia from '@/components/sections/faq/FaqSplitMedia';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSplitMedia
          tag="Common Questions"
          title="Need More Clarity?"
          description="Here is what our clients ask most."
          items={[
            {
              question: "How long for a new site?",
              answer: "Usually 2-4 weeks depending on scope.",
            },
            {
              question: "Do you offer SEO?",
              answer: "Yes, local SEO is baked into every build.",
            },
            {
              question: "How does AI help?",
              answer: "It handles bookings and answers 24/7.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/business-team-talking-about-statistics_53876-94908.jpg"
        />
        </SectionErrorBoundary>
      </div>
  );
}
