// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "industries" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function IndustriesSection(): React.JSX.Element {
  return (
    <div id="industries" data-section="industries">
        <SectionErrorBoundary name="industries">
              <FeaturesRevealCardsBento
          tag="Who We Serve"
          title="Partnering with Local Heroes"
          description="Tailored strategies for service-based businesses."
          items={[
            {
              title: "Restaurants",
              description: "Online ordering & reservation systems.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/business-evaluation-information-growth-concept_53876-125573.jpg",
            },
            {
              title: "Contractors",
              description: "Lead generation funnels for jobs.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/3d-rendering-biorobots-concept_23-2149524399.jpg",
            },
            {
              title: "Medical Clinics",
              description: "Booking automation & SEO.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/startup-worker-uses-laptop-open-space-reviewing-project-data-documents-workstation-executive-assistant-working-marketing-strategy-business-development-ai-developer_482257-65810.jpg",
            },
            {
              title: "Auto Repair",
              description: "Local search dominance.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/army-soldier-reviews-targets-satellite-world-map-ensure-global-protection_482257-91236.jpg",
            },
            {
              title: "Professional Services",
              description: "High-ticket sales funnels.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/arrow-with-bright-neon-colors_23-2151204924.jpg",
            },
            {
              title: "Home Maintenance",
              description: "Service scheduling workflows.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/workers-it-company-working-computer_1303-19431.jpg",
            },
            {
              title: "Dental Offices",
              description: "Patient acquisition funnels.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/woman-using-transparent-tablet-couch-innovative-technology_53876-97924.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
