// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesDetailedSteps from '@/components/sections/features/FeaturesDetailedSteps';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesDetailedSteps
          tag="Our Expertise"
          title="Full-Stack Digital Growth"
          description="We don't just build websites; we create engines for your business growth."
          steps={[
            {
              tag: "Development",
              title: "Web Design",
              subtitle: "Modern, fast, mobile-ready",
              description: "High-converting websites built to impress.",
              imageSrc: "http://img.b2bpic.net/free-photo/content-marketing-social-media-advertising-commercial-branding-concept_53876-15878.jpg",
            },
            {
              tag: "Visibility",
              title: "SEO Optimization",
              subtitle: "Rank #1 on Google",
              description: "Capture local search intent effortlessly.",
              imageSrc: "http://img.b2bpic.net/free-photo/abstract-technology-background-concept_1194-617185.jpg",
            },
            {
              tag: "Automation",
              title: "AI Integration",
              subtitle: "24/7 Virtual Assistants",
              description: "AI chatbots that qualify and book leads.",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-entrepreneur-with-corporate-job-looking-camera-business-office-portrait-young-man-preparing-work-planning-development-industry-with-technology-computer_482257-29387.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
