// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialColumnMarqueeCards from '@/components/sections/testimonial/TestimonialColumnMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialColumnMarqueeCards
          tag="Client Success"
          title="Driving Real Results"
          description="Don't take our word for it."
          testimonials={[
            {
              name: "Mark R.",
              role: "Restaurant Owner",
              quote: "Tafakkur doubled our monthly reservations.",
              imageSrc: "http://img.b2bpic.net/free-photo/3d-flowing-particles-network-communications-design_1048-15848.jpg",
            },
            {
              name: "Sarah J.",
              role: "Clinic Director",
              quote: "The AI chatbot saved my staff hours daily.",
              imageSrc: "http://img.b2bpic.net/free-vector/data-concept-technology-background_23-2148293185.jpg",
            },
            {
              name: "Mike D.",
              role: "Plumber",
              quote: "My new site ranks for all our keywords.",
              imageSrc: "http://img.b2bpic.net/free-photo/rear-view-polygraph-examiner-works-office-with-his-lie-detector-s-equipment_146671-17277.jpg",
            },
            {
              name: "Emily P.",
              role: "Dental CEO",
              quote: "Increased our new patient leads by 40%.",
              imageSrc: "http://img.b2bpic.net/free-photo/representation-user-experience-interface-design_23-2150169842.jpg",
            },
            {
              name: "Dave L.",
              role: "Auto Shop Owner",
              quote: "The most professional agency I've used.",
              imageSrc: "http://img.b2bpic.net/free-vector/music-equalizer-technology-blue-background-with-digital-sound-wave_53876-119609.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
